/**
 * Complete registry of all 254 Texas counties with their 5-digit FIPS codes
 * (state 48 + county code). Auto-derived from the US Census national county
 * file. This is the county identity layer the whole app keys on — boost slot
 * caps, parcel data, and listing geography are all resolved through FIPS, so a
 * per-county limit works uniformly for every Texas county, not just the launch
 * footprint.
 */

export type TxCounty = { fips: string; name: string };

export const TX_COUNTIES: TxCounty[] = [
  { fips: "48001", name: "Anderson County" },
  { fips: "48003", name: "Andrews County" },
  { fips: "48005", name: "Angelina County" },
  { fips: "48007", name: "Aransas County" },
  { fips: "48009", name: "Archer County" },
  { fips: "48011", name: "Armstrong County" },
  { fips: "48013", name: "Atascosa County" },
  { fips: "48015", name: "Austin County" },
  { fips: "48017", name: "Bailey County" },
  { fips: "48019", name: "Bandera County" },
  { fips: "48021", name: "Bastrop County" },
  { fips: "48023", name: "Baylor County" },
  { fips: "48025", name: "Bee County" },
  { fips: "48027", name: "Bell County" },
  { fips: "48029", name: "Bexar County" },
  { fips: "48031", name: "Blanco County" },
  { fips: "48033", name: "Borden County" },
  { fips: "48035", name: "Bosque County" },
  { fips: "48037", name: "Bowie County" },
  { fips: "48039", name: "Brazoria County" },
  { fips: "48041", name: "Brazos County" },
  { fips: "48043", name: "Brewster County" },
  { fips: "48045", name: "Briscoe County" },
  { fips: "48047", name: "Brooks County" },
  { fips: "48049", name: "Brown County" },
  { fips: "48051", name: "Burleson County" },
  { fips: "48053", name: "Burnet County" },
  { fips: "48055", name: "Caldwell County" },
  { fips: "48057", name: "Calhoun County" },
  { fips: "48059", name: "Callahan County" },
  { fips: "48061", name: "Cameron County" },
  { fips: "48063", name: "Camp County" },
  { fips: "48065", name: "Carson County" },
  { fips: "48067", name: "Cass County" },
  { fips: "48069", name: "Castro County" },
  { fips: "48071", name: "Chambers County" },
  { fips: "48073", name: "Cherokee County" },
  { fips: "48075", name: "Childress County" },
  { fips: "48077", name: "Clay County" },
  { fips: "48079", name: "Cochran County" },
  { fips: "48081", name: "Coke County" },
  { fips: "48083", name: "Coleman County" },
  { fips: "48085", name: "Collin County" },
  { fips: "48087", name: "Collingsworth County" },
  { fips: "48089", name: "Colorado County" },
  { fips: "48091", name: "Comal County" },
  { fips: "48093", name: "Comanche County" },
  { fips: "48095", name: "Concho County" },
  { fips: "48097", name: "Cooke County" },
  { fips: "48099", name: "Coryell County" },
  { fips: "48101", name: "Cottle County" },
  { fips: "48103", name: "Crane County" },
  { fips: "48105", name: "Crockett County" },
  { fips: "48107", name: "Crosby County" },
  { fips: "48109", name: "Culberson County" },
  { fips: "48111", name: "Dallam County" },
  { fips: "48113", name: "Dallas County" },
  { fips: "48115", name: "Dawson County" },
  { fips: "48117", name: "Deaf Smith County" },
  { fips: "48119", name: "Delta County" },
  { fips: "48121", name: "Denton County" },
  { fips: "48123", name: "DeWitt County" },
  { fips: "48125", name: "Dickens County" },
  { fips: "48127", name: "Dimmit County" },
  { fips: "48129", name: "Donley County" },
  { fips: "48131", name: "Duval County" },
  { fips: "48133", name: "Eastland County" },
  { fips: "48135", name: "Ector County" },
  { fips: "48137", name: "Edwards County" },
  { fips: "48139", name: "Ellis County" },
  { fips: "48141", name: "El Paso County" },
  { fips: "48143", name: "Erath County" },
  { fips: "48145", name: "Falls County" },
  { fips: "48147", name: "Fannin County" },
  { fips: "48149", name: "Fayette County" },
  { fips: "48151", name: "Fisher County" },
  { fips: "48153", name: "Floyd County" },
  { fips: "48155", name: "Foard County" },
  { fips: "48157", name: "Fort Bend County" },
  { fips: "48159", name: "Franklin County" },
  { fips: "48161", name: "Freestone County" },
  { fips: "48163", name: "Frio County" },
  { fips: "48165", name: "Gaines County" },
  { fips: "48167", name: "Galveston County" },
  { fips: "48169", name: "Garza County" },
  { fips: "48171", name: "Gillespie County" },
  { fips: "48173", name: "Glasscock County" },
  { fips: "48175", name: "Goliad County" },
  { fips: "48177", name: "Gonzales County" },
  { fips: "48179", name: "Gray County" },
  { fips: "48181", name: "Grayson County" },
  { fips: "48183", name: "Gregg County" },
  { fips: "48185", name: "Grimes County" },
  { fips: "48187", name: "Guadalupe County" },
  { fips: "48189", name: "Hale County" },
  { fips: "48191", name: "Hall County" },
  { fips: "48193", name: "Hamilton County" },
  { fips: "48195", name: "Hansford County" },
  { fips: "48197", name: "Hardeman County" },
  { fips: "48199", name: "Hardin County" },
  { fips: "48201", name: "Harris County" },
  { fips: "48203", name: "Harrison County" },
  { fips: "48205", name: "Hartley County" },
  { fips: "48207", name: "Haskell County" },
  { fips: "48209", name: "Hays County" },
  { fips: "48211", name: "Hemphill County" },
  { fips: "48213", name: "Henderson County" },
  { fips: "48215", name: "Hidalgo County" },
  { fips: "48217", name: "Hill County" },
  { fips: "48219", name: "Hockley County" },
  { fips: "48221", name: "Hood County" },
  { fips: "48223", name: "Hopkins County" },
  { fips: "48225", name: "Houston County" },
  { fips: "48227", name: "Howard County" },
  { fips: "48229", name: "Hudspeth County" },
  { fips: "48231", name: "Hunt County" },
  { fips: "48233", name: "Hutchinson County" },
  { fips: "48235", name: "Irion County" },
  { fips: "48237", name: "Jack County" },
  { fips: "48239", name: "Jackson County" },
  { fips: "48241", name: "Jasper County" },
  { fips: "48243", name: "Jeff Davis County" },
  { fips: "48245", name: "Jefferson County" },
  { fips: "48247", name: "Jim Hogg County" },
  { fips: "48249", name: "Jim Wells County" },
  { fips: "48251", name: "Johnson County" },
  { fips: "48253", name: "Jones County" },
  { fips: "48255", name: "Karnes County" },
  { fips: "48257", name: "Kaufman County" },
  { fips: "48259", name: "Kendall County" },
  { fips: "48261", name: "Kenedy County" },
  { fips: "48263", name: "Kent County" },
  { fips: "48265", name: "Kerr County" },
  { fips: "48267", name: "Kimble County" },
  { fips: "48269", name: "King County" },
  { fips: "48271", name: "Kinney County" },
  { fips: "48273", name: "Kleberg County" },
  { fips: "48275", name: "Knox County" },
  { fips: "48277", name: "Lamar County" },
  { fips: "48279", name: "Lamb County" },
  { fips: "48281", name: "Lampasas County" },
  { fips: "48283", name: "La Salle County" },
  { fips: "48285", name: "Lavaca County" },
  { fips: "48287", name: "Lee County" },
  { fips: "48289", name: "Leon County" },
  { fips: "48291", name: "Liberty County" },
  { fips: "48293", name: "Limestone County" },
  { fips: "48295", name: "Lipscomb County" },
  { fips: "48297", name: "Live Oak County" },
  { fips: "48299", name: "Llano County" },
  { fips: "48301", name: "Loving County" },
  { fips: "48303", name: "Lubbock County" },
  { fips: "48305", name: "Lynn County" },
  { fips: "48307", name: "McCulloch County" },
  { fips: "48309", name: "McLennan County" },
  { fips: "48311", name: "McMullen County" },
  { fips: "48313", name: "Madison County" },
  { fips: "48315", name: "Marion County" },
  { fips: "48317", name: "Martin County" },
  { fips: "48319", name: "Mason County" },
  { fips: "48321", name: "Matagorda County" },
  { fips: "48323", name: "Maverick County" },
  { fips: "48325", name: "Medina County" },
  { fips: "48327", name: "Menard County" },
  { fips: "48329", name: "Midland County" },
  { fips: "48331", name: "Milam County" },
  { fips: "48333", name: "Mills County" },
  { fips: "48335", name: "Mitchell County" },
  { fips: "48337", name: "Montague County" },
  { fips: "48339", name: "Montgomery County" },
  { fips: "48341", name: "Moore County" },
  { fips: "48343", name: "Morris County" },
  { fips: "48345", name: "Motley County" },
  { fips: "48347", name: "Nacogdoches County" },
  { fips: "48349", name: "Navarro County" },
  { fips: "48351", name: "Newton County" },
  { fips: "48353", name: "Nolan County" },
  { fips: "48355", name: "Nueces County" },
  { fips: "48357", name: "Ochiltree County" },
  { fips: "48359", name: "Oldham County" },
  { fips: "48361", name: "Orange County" },
  { fips: "48363", name: "Palo Pinto County" },
  { fips: "48365", name: "Panola County" },
  { fips: "48367", name: "Parker County" },
  { fips: "48369", name: "Parmer County" },
  { fips: "48371", name: "Pecos County" },
  { fips: "48373", name: "Polk County" },
  { fips: "48375", name: "Potter County" },
  { fips: "48377", name: "Presidio County" },
  { fips: "48379", name: "Rains County" },
  { fips: "48381", name: "Randall County" },
  { fips: "48383", name: "Reagan County" },
  { fips: "48385", name: "Real County" },
  { fips: "48387", name: "Red River County" },
  { fips: "48389", name: "Reeves County" },
  { fips: "48391", name: "Refugio County" },
  { fips: "48393", name: "Roberts County" },
  { fips: "48395", name: "Robertson County" },
  { fips: "48397", name: "Rockwall County" },
  { fips: "48399", name: "Runnels County" },
  { fips: "48401", name: "Rusk County" },
  { fips: "48403", name: "Sabine County" },
  { fips: "48405", name: "San Augustine County" },
  { fips: "48407", name: "San Jacinto County" },
  { fips: "48409", name: "San Patricio County" },
  { fips: "48411", name: "San Saba County" },
  { fips: "48413", name: "Schleicher County" },
  { fips: "48415", name: "Scurry County" },
  { fips: "48417", name: "Shackelford County" },
  { fips: "48419", name: "Shelby County" },
  { fips: "48421", name: "Sherman County" },
  { fips: "48423", name: "Smith County" },
  { fips: "48425", name: "Somervell County" },
  { fips: "48427", name: "Starr County" },
  { fips: "48429", name: "Stephens County" },
  { fips: "48431", name: "Sterling County" },
  { fips: "48433", name: "Stonewall County" },
  { fips: "48435", name: "Sutton County" },
  { fips: "48437", name: "Swisher County" },
  { fips: "48439", name: "Tarrant County" },
  { fips: "48441", name: "Taylor County" },
  { fips: "48443", name: "Terrell County" },
  { fips: "48445", name: "Terry County" },
  { fips: "48447", name: "Throckmorton County" },
  { fips: "48449", name: "Titus County" },
  { fips: "48451", name: "Tom Green County" },
  { fips: "48453", name: "Travis County" },
  { fips: "48455", name: "Trinity County" },
  { fips: "48457", name: "Tyler County" },
  { fips: "48459", name: "Upshur County" },
  { fips: "48461", name: "Upton County" },
  { fips: "48463", name: "Uvalde County" },
  { fips: "48465", name: "Val Verde County" },
  { fips: "48467", name: "Van Zandt County" },
  { fips: "48469", name: "Victoria County" },
  { fips: "48471", name: "Walker County" },
  { fips: "48473", name: "Waller County" },
  { fips: "48475", name: "Ward County" },
  { fips: "48477", name: "Washington County" },
  { fips: "48479", name: "Webb County" },
  { fips: "48481", name: "Wharton County" },
  { fips: "48483", name: "Wheeler County" },
  { fips: "48485", name: "Wichita County" },
  { fips: "48487", name: "Wilbarger County" },
  { fips: "48489", name: "Willacy County" },
  { fips: "48491", name: "Williamson County" },
  { fips: "48493", name: "Wilson County" },
  { fips: "48495", name: "Winkler County" },
  { fips: "48497", name: "Wise County" },
  { fips: "48499", name: "Wood County" },
  { fips: "48501", name: "Yoakum County" },
  { fips: "48503", name: "Young County" },
  { fips: "48505", name: "Zapata County" },
  { fips: "48507", name: "Zavala County" },
];

const BY_FIPS = new Map(TX_COUNTIES.map((c) => [c.fips, c.name]));

function normalizeName(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/\s+county$/, "")
    .replace(/\s+/g, " ");
}

const BY_NAME = new Map(
  TX_COUNTIES.map((c) => [normalizeName(c.name), c.fips]),
);

/** Resolve a county name ("Polk", "Polk County", " polk ") to its FIPS code. */
export function txCountyFipsByName(name: string | null | undefined): string | null {
  if (!name) return null;
  return BY_NAME.get(normalizeName(name)) ?? null;
}

/** Resolve a FIPS code ("48373") to its canonical county name. */
export function txCountyNameByFips(fips: string | null | undefined): string | null {
  if (!fips) return null;
  return BY_FIPS.get(fips.trim()) ?? null;
}

/** True when the string is a valid Texas county FIPS code. */
export function isTxCountyFips(fips: string | null | undefined): boolean {
  return !!fips && BY_FIPS.has(fips.trim());
}
