-- DEPRECATED — superseded by the versioned migrations in supabase/migrations/.
--
-- Apply order for a real Supabase project (SQL editor or `supabase db push`):
--   1) supabase/migrations/0001_init.sql   -- schema, helpers, auth trigger
--   2) supabase/migrations/0002_rls.sql    -- Row Level Security policies
--
-- Local RLS verification (plain Postgres, no Supabase needed):
--   supabase/test/00_shim.sql   -- emulates auth schema + anon/authenticated roles
--   then 0001_init.sql, 0002_rls.sql
--   supabase/test/10_scenario.sql + supabase/test/20_assert.sql
--
-- The migrations cover every blueprint entity: profiles, brokerages, teams,
-- team_members, listings (marketplace + pro/editable), listing_analytics,
-- suites/suite_items, follows, messages, buyers, seller_clients, referrals,
-- inquiries, lead_claims, channels, threads, posts, library_folders,
-- questions/answers, and the county-capped boost tables.
