-- Generated by scripts/ingest-polk.mjs — real Polk CAD parcel data.
-- Safe to re-run (idempotent upserts).

insert into public.county_parcels (
  source, county_fips, prop_id, geo_id, owner_name, situs_num, situs_street, situs_city, situs_state, situs_zip, situs_address, legal_description, abstract_subdivision_code, tract_or_lot, block, legal_acreage, land_value, improvement_value, market_value, tax_year, school_code, geojson, centroid_lat, centroid_lng, source_url
) values
  ('polk_cad', '48373', '28815', '11053000115', 'NEAL JOHN & MELISSA', '243', 'FAITH', 'LIVINGSTON', 'TX', '77351', '243 FAITH LN', 'ABST 1053 E H WALDREP SURVEY TRACT 1-C', '11053', '1-C', null, 5.7973, 102973, 104228, 207201, 2027, 'ILV', '{"type":"Polygon","coordinates":[[[-94.9153639197385,30.6775248758999],[-94.9153433807698,30.6760658595149],[-94.9153974223316,30.6760822592303],[-94.9154039324051,30.6761249084448],[-94.9154864568666,30.6761104067559],[-94.9155752906235,30.6761025914605],[-94.9157687134522,30.6760182826498],[-94.9158591388685,30.676061253534],[-94.9159430853792,30.6759293189877],[-94.9160949569661,30.6758573866631],[-94.9161507164408,30.675882846777],[-94.9161941826048,30.675862848181],[-94.9163216201526,30.6758290495636],[-94.9164291035242,30.6757802865222],[-94.916436873572,30.6757478703042],[-94.9164079343836,30.6757209705606],[-94.9164342295315,30.6756893328757],[-94.9165043940558,30.675709622046],[-94.9166245100226,30.6756607488152],[-94.9165809269383,30.6755510528702],[-94.9166115307045,30.67545716955],[-94.9166168508037,30.6754408511862],[-94.9166513525946,30.675421758255],[-94.9166902658962,30.6754298179748],[-94.9167065217919,30.6771785234151],[-94.915982077599,30.6771861736092],[-94.9160788885708,30.6778079242688],[-94.9159863211205,30.677807765756],[-94.9159890891799,30.6776361283574],[-94.9153639197385,30.6775248758999]]]}'::jsonb, 30.6762068, -94.9160999, 'https://utility.arcgis.com/usrsvcs/servers/60f9b6d8a8c546b6b0aa1fb4999bee8e/rest/services/PolkCADWebService/FeatureServer/0'),
  ('polk_cad', '48373', '19674', '10406000200', 'NEAL JOHN & MELISSA', '243', 'FAITH LN', 'LIVINGSTON', 'TX', '77351', '243 FAITH LN', 'ABST 406 A LOWE SURVEY TRACT 4C', '10406', '4C', null, 1, 26000, 176248, 202248, 2027, 'ILV', '{"type":"Polygon","coordinates":[[[-94.9147225893265,30.6784146411068],[-94.9156669957649,30.6784186812484],[-94.9154212783555,30.6788592542315],[-94.9153136350721,30.6789110968875],[-94.9147363293442,30.6789126618645],[-94.9147225893265,30.6784146411068]]]}'::jsonb, 30.6786552, -94.9150972, 'https://utility.arcgis.com/usrsvcs/servers/60f9b6d8a8c546b6b0aa1fb4999bee8e/rest/services/PolkCADWebService/FeatureServer/0')
on conflict (source, prop_id) do update set
  county_fips = excluded.county_fips, geo_id = excluded.geo_id, owner_name = excluded.owner_name, situs_num = excluded.situs_num, situs_street = excluded.situs_street, situs_city = excluded.situs_city, situs_state = excluded.situs_state, situs_zip = excluded.situs_zip, situs_address = excluded.situs_address, legal_description = excluded.legal_description, abstract_subdivision_code = excluded.abstract_subdivision_code, tract_or_lot = excluded.tract_or_lot, block = excluded.block, legal_acreage = excluded.legal_acreage, land_value = excluded.land_value, improvement_value = excluded.improvement_value, market_value = excluded.market_value, tax_year = excluded.tax_year, school_code = excluded.school_code, geojson = excluded.geojson, centroid_lat = excluded.centroid_lat, centroid_lng = excluded.centroid_lng, source_url = excluded.source_url;

insert into public.county_parcel_values (
  source, prop_id, tax_year, land_value, improvement_value, market_value
) values
  ('polk_cad', '28815', 2027, 102973, 104228, 207201),
  ('polk_cad', '19674', 2027, 26000, 176248, 202248)
on conflict (source, prop_id, tax_year) do update set
  land_value = excluded.land_value,
  improvement_value = excluded.improvement_value,
  market_value = excluded.market_value;
